#+title: Comptia A+ Study Guide
#+author: Travis Willison
#+date: <2023-11-09 Thu>

* Chapter 3: CPUS
** Learning Objectives
1. Identify the core components of a CPU
2. Describe the relationship of CPUs with memory
3. Explain the varieties of modern CPUs
4. Select and install a CPU
5. Troubleshoot CPUs
** CPU Core Components
*** The Man in the Box
*** Registers
*** Clock
*** Back to the External Data Bus
** Memory
*** Memory and RAM
*** Address Bus
** Modern CPUs
*** Developers
*** Technology
** Selecting and Installing CPUs
*** Selecting a CPU
*** Installation Issues
** Troubleshooting CPUs
*** Symptoms of Overheating
*** Catastrophic Failure
*** Intel Core M
** Chapter Review
* Chapter 12: Windows Under the Hood
** Learning Objectives
1. Work with the Registry
2. Understand and Observe the Windows Boot Process
3. Manage processes, services, and threads
4. Explore Windows tools for Programmers
** Registry
The registry is a database that contains everything about a PC that is part of every Windows system.
This includes hardware info, network info, user preferences, file types, passwords, etc.
It is essential to operate Windows, a Windows computer won't boot without the registry.

Windows stores these registry files, called hives, in both the `\%SystemRoot%\System32\config` folder and in each user folder.
It is not common to need to access these folders directly and there are plenty of options to edit these files.
It is not necessarily a test objective, however, it is helpful to understand and be able to manipulate the Windows Registry.
*** Accessing the Registry
Rarely will a tech touch the registry directly, yet when a person uses utilities such as Settings or Control Panel, the registry is changed.
Before looking at registry, one should be familiar with regedit which is the Registry Editor and can be accessed from the Start/Seach Bar as well as being execuatable from the command line.
*** Registry Components
The registry is organized in a tree structure.
When opened, the Registry Editor will display 5 main subgroups (the root keys):
1. HKEY_CLASSES_ROOT
2. HKEY_CURRENT_USER
3. HEKY_LOCAL_MACHINE
4. HKEY_USERS
5. HKEY_CURRENT_CONFIG
When one of these root are selected the editor will display subkeys below it.
Note that subkeys can have subkeys within it and these subkeys all have values assigned to them.
Values define aspects of a subkey.
Each root key has a specific function.
**** HKEY_CLASSES_ROOT
This registry key defines standard class objects used by Windows.
A class object is a group of functions that defines interaction with said object.
Most everything on the file system interacts with class objects.
As an example, the registry has two class objects that define a JPG image.
One object is located at `HKEY_CLASSES_ROOT` and one at `HKEY_CURRENT_USER\Software\Classes`(this one covers user-associations for JPG files).
This key combines class objects from `HKEY_CURRENT_USER` and `HKEY_LOCAL_MACHINE` to provide backwards compatibility.
**** HKEY_CURRENT_USER and HKEY_USERS
These two keys store personalization information such as wallpapers, screensavers, and desktop contents.
Current user is for the current logged on user, and users is for all users on the system.
**** HKEY_LOCAL_MACHINE
This key contains all data for non-user-specific configurations; including all devices and programs attached to the computer.
**** HKEY_CURRENT_CONFIG
If a key has multiple values, such as if a computer has multiple monitor configurations, the currently used configuration is the one value stored here.
Due to the scant settings with multiple options being rarely used, such as having a second monitor, this key is rarely touched.
*** Talking Registry
Values in a key have a defined data type:
1. String value: most flexible type, vey common, can have any form of data.
2. Binary value: strings of 1's and 0's.
3. DWORD value: binary strings limited to 32 bits.
4. QWORD value: binary strings limited to 64 bits.
*** Manual Registry Edits
This is a very direct and risky way of managing the registry, as mistakes can break functionality in Windows.
A way to guard against permanent damage, it is best practice to save a backup of the registry before any manual edits.
A more common registry edit is to delete autostarting programs.
*** Command-Line Registry Editing Tools
Windows is packaged with a few CLI tools to manage the registry, with more included in Powershell.
The two important tools are `reg` and `regsvr32`: `reg` is a full registry editing tool, whereas `regsvr32` is only able to add(or register) DLL files as command components.
** The Boot Process
Windows currently supports both BIOS and UEFI boot processes, and determining which one is the first step of the boot process.
After checking, the process branches differently based on which system scheme is used(MBR or UEFI).
For MBR-BIOS: the BIOS scans a hard drive for a master boot record(MBR). The MBR holds a bit of the file system that scans the partition table for teh system partition and loads the boot sector. The boot sector contains code that points to `bootmgr`, the boot manager.
For UEFI: UEFI loads the boot manager directly.
** Applications, Processes, and Services
For Windows, programs are executable files that wait on mass storage.
Windows then loads everything into RAM as a process.
The CPU then reads that process and the process points the CPU to the code to run.
In the abstract, running and managing processes is the majority of what Windows does.
Windows is a multitasking system, so there are usually many processes occuring simultaneously.
Many of these processes happen at the time a window is on teh screen, these processes working together are what is commonly called an application.
There are groups of processes that run without a graphical interface, in the background, and these are services.
*** Task Manager
Task manager is a graphical interface that allows a user to look at all the applications, processes, and services running at any given time.
Tasks are also processes, so they show up in both tabs of Task Manager.
Task manager allows the user to not only view, sort, and kill tasks; Task Manager also lets a user change the priority of a program and directing processes to other CPU cores.
Force quit isn't the only option for stopping a process that Task Manager, End Process Tree quits not only the selected process but all processes dependent on the originally selected one.
Task Manager can also monitor network processing as well.
It also cn display autostart programs.
*** Resource Monitor
*** Performance Tools
** Tools for Programmers
*** Component Services
*** Data Sources
** Chapter Review
* Chapter 13: Users, Groups, and Permissions
** Learning Objectives
1. Create and administer Windows users and groups
2. Define and use NTFS permissions for authorization
3. Share a Windows computer securely
4. Secure PCs with policies and User Account Control
** Authentication with Users and Groups
*** User Accounts
*** Passwords
*** Groups
*** Standard User and Elevated Privileges
*** Configuring Users and Groups in Windows
** Authorization Through NTFS
*** NTFS Permissions
*** Inheritance
*** Permission Propagation
*** Techs and Permissions
*** Permissions in Linux and macOS
** Sharing Resources Securely
*** Sharing Folders and Files
*** Locating Shared Folders
*** Administrative Shares
*** Protecting Data with Encryption
** Beyond Sharing Resources
*** Security Policies
*** User Account Control
*** How UAC Works
*** UAC in Modern Windows
** Chapter Review
